# Generated by Django 4.0 on 2022-11-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_message_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_see',
            field=models.BooleanField(default=False),
        ),
    ]
